export enum ACTIONS {
  CURRENCIES_REQUEST_DATA = 'CURRENCIES_REQUEST_DATA',
  CURRENCIES_RECEIVE_DATA = 'CURRENCIES_RECEIVE_DATA',
  CURRENCIES_REJECT_DATA = 'CURRENCIES_REJECT_DATA',
  CURRENCIES_REQUEST_END = 'CURRENCIES_REQUEST_END',
}
